# ============================================
# Application Configuration
# ============================================
spring.application.name=taskmanagement
server.port=8085

# ============================================
# Kafka Configuration
# ============================================
spring.kafka.bootstrap-servers=localhost:9092

spring.main.lazy-initialization=true


# --- Producer Configuration ---
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
# Optional but recommended for JSON
spring.kafka.producer.properties.spring.json.add.type.headers=false

# --- Consumer Configuration ---
spring.kafka.consumer.group-id=taskmanagement-group
spring.kafka.consumer.auto-offset-reset=earliest

# Use ErrorHandlingDeserializer for safe deserialization
spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Delegate deserializers
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# JSON configuration for consumer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.home.employee_service.events.TaskEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.kafka.producer.transaction-id-prefix=employee-tx-
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3

# Disable auto-startup of listeners (useful for tests)
spring.kafka.listener.auto-startup=false

# ============================================
# MySQL Configuration
# ============================================
#spring.datasource.url=jdbc:mysql://host.docker.internal:3306/ganeshdb
spring.datasource.url=jdbc:mysql://localhost:3306/ganeshdb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ============================================
# JPA / Hibernate Configuration
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ============================================
# Logging Configuration
# ============================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.zaxxer.hikari=DEBUG
